# Generated by Django 3.2 on 2022-05-23 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.chat', verbose_name='Чат')),
            ],
        ),
    ]
