# Generated by Django 3.2 on 2022-05-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=35, verbose_name='Пользователь')),
                ('user_id', models.CharField(max_length=35, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
