# Generated by Django 3.2 on 2022-05-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20220526_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_id',
            field=models.IntegerField(null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(default='', max_length=350, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
