# Generated by Django 3.2 on 2022-05-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_auto_20220530_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
